// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Softcase_ML
{
    public partial class ModeloOcupacao
    {
        /// <summary>
        /// model input class for ModeloOcupacao.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Hora")]
            public float Hora { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"DiaDaSemana")]
            public float DiaDaSemana { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Temperatura")]
            public float Temperatura { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Chuva")]
            public float Chuva { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"EventoNaRegiao")]
            public float EventoNaRegiao { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"EhFeriado")]
            public float EhFeriado { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Ocupacao")]
            public float Ocupacao { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ModeloOcupacao.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Hora")]
            public float Hora { get; set; }

            [ColumnName(@"DiaDaSemana")]
            public float DiaDaSemana { get; set; }

            [ColumnName(@"Temperatura")]
            public float Temperatura { get; set; }

            [ColumnName(@"Chuva")]
            public float Chuva { get; set; }

            [ColumnName(@"EventoNaRegiao")]
            public float EventoNaRegiao { get; set; }

            [ColumnName(@"EhFeriado")]
            public float EhFeriado { get; set; }

            [ColumnName(@"Ocupacao")]
            public float Ocupacao { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ModeloOcupacao.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
